require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 150

Rails/FilePath:
  Exclude:
    - spec/rails_helper.rb
