inherit_from:
  - .rubocop_rspec.yml
  - .rubocop_rails.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
